apiVersion: v1
kind: Service
metadata:
  name: nginx-service-a
spec:
  selector:
    app: nginx
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80
      targetPort: http-web-svc
